openapi: 3.0.0
info:
  title: Backend-Documentation
  version: 1.0.0
  description: ""
servers:
  - url: "{{base_url}}"
  - url: "{{baseUrl}}"
  - url: api
paths:
  /api/auth/login:
    post:
      summary: Login
      responses:
        "200":
          description: Success Login
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Wed, 07 Jan 2026 01:58:48 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Auth
      description: |-
        **Endpoint Login Manual**

        Digunakan untuk menukarkan email dan password menjadi Token Akses.

        **Body Params (JSON):**

        - `email` (required): Email terdaftar.
            
        - `password` (required): Password user.
            

        **Response:**

        - `access_token`: Token Sanctum (Bearer Token).
            
        - `user`: Data detail user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
            example:
              email: admin@saladdin.com
              password: password
  /api/logout:
    post:
      summary: Logout
      responses:
        "200":
          description: Success Logout
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Wed, 07 Jan 2026 02:02:07 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Auth
      description: >-
        **Logout (Hapus Token)**


        Menghapus/menghanguskan token yang sedang digunakan, sehingga tidak bisa
        dipakai lagi.


        **Headers:**


        - `Authorization`: `Bearer`
  /api/auth/register:
    post:
      summary: Register
      responses:
        "201":
          description: Success Register
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Wed, 07 Jan 2026 02:01:21 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Auth
      description: >-
        **Endpoint Pendaftaran User Baru**


        Endpoint ini digunakan untuk mendaftarkan siswa baru secara manual
        (email & password).


        **Body Params (JSON):**


        - `name` (required, string): Nama lengkap.
            
        - `email` (required, email, unique): Alamat email.
            
        - `password` (required, min 8 chars): Password.
            
        - `password_confirmation` (required): Harus sama dengan password.
            

        **Response:**  

        Mengembalikan `access_token` yang harus disimpan untuk sesi login.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                password_confirmation:
                  type: string
            example:
              name: New Student 2
              email: student2@test.com
              password: password123
              password_confirmation: password123
  /api/me:
    get:
      summary: Get Profile
      responses:
        "200":
          description: Success Get Profile
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Wed, 07 Jan 2026 02:00:03 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Auth
      description: >-
        **Cek Data User Login (Me)**


        Endpoint untuk mengambil data profil user yang sedang login berdasarkan
        Token yang dikirim.


        **Headers:**


        - `Authorization`: `Bearer`
            
        - `Accept`: `application/json`
  /api/auth/google:
    get:
      summary: Initiate Google Login/Register
      responses: {}
      tags:
        - Auth
      description: "### ⚠️ PENTING: Jangan di-fetch!\n\nEndpoint ini **BUKAN** untuk dipanggil menggunakan `axios.get()` atau `fetch()`.  \nEndpoint ini berfungsi untuk **Redirect Browser** ke halaman persetujuan Google.\n\n### Cara Penggunaan di Frontend:\n\nGunakan tag anchor HTML biasa (`[](null)`[) atau <code>window.location.href</code>:](null)[<br>Login with Google<br>](http://127.0.0.1:8000/api/auth/google)\n\nBuatlah halaman di\_/auth/callback, lalu ambil\_token\_dari URL parameter dan simpan ke Cookies/LocalStorageEndFragment"
  /api/auth/google/callback:
    get:
      summary: Handle Callback (Saat user balik dari Google)
      responses: {}
      tags:
        - Auth
  /api/lessons/{lessonId}/questions/{seq}:
    get:
      summary: Get Question Quiz by ID
      responses:
        "200":
          description: Success Get Question Quiz by ID
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 16 Jan 2026 10:19:03 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Student
        - Courses
        - Course Detail
        - Quiz
    parameters:
      - name: lessonId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "4"
      - name: seq
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "1"
  /api/lessons/{lessonId}/submit-quiz:
    post:
      summary: Submit Quiz
      responses:
        "200":
          description: Success Submit Quiz
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 16 Jan 2026 10:21:22 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Student
        - Courses
        - Course Detail
        - Quiz
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                answers:
                  type: object
                  properties:
                    "1":
                      type: integer
            example:
              answers:
                "1": 5
    parameters:
      - name: lessonId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "4"
  /api/quiz-attempts/1/review:
    get:
      summary: Get Review Quiz Attempt
      responses:
        "200":
          description: Success Get Review Quiz Attempt
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 16 Jan 2026 10:28:34 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Student
        - Courses
        - Course Detail
        - Quiz
      requestBody:
        content:
          application/json:
            schema:
              type: object
  /api/courses/{slug}:
    get:
      summary: Get Course Detail By Slug (Public)
      responses:
        "200":
          description: Success Get Course Detail By Slug (Public)
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 30 Jan 2026 09:48:37 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Student
        - Courses
        - Course Detail
    parameters:
      - name: slug
        in: path
        required: true
        deprecated: false
        schema: {}
        example: sejarah-masjidil-aqsa-baitul-maqdis
  /api/lessons/{lessonId}:
    get:
      summary: Get Lesson By ID
      responses:
        "200":
          description: Success File Document Type
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Sat, 10 Jan 2026 14:47:49 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
        "403":
          description: Fail Get Lesson By ID
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 16 Jan 2026 10:05:41 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Student
        - Courses
        - Course Detail
    parameters:
      - name: lessonId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "4"
  /api/lessons/{lessonId}/complete:
    post:
      summary: Complete Lesson
      responses:
        "200":
          description: Success Complete Lesson
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 16 Jan 2026 07:49:28 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
        "403":
          description: Fail Complete Lesson
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 16 Jan 2026 10:16:00 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Student
        - Courses
        - Course Detail
    parameters:
      - name: lessonId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "4"
  /api/courses:
    get:
      summary: Get All Courses
      responses:
        "200":
          description: Success Get All Courses
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Sat, 10 Jan 2026 06:40:59 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Student
        - Courses
  /api/my-courses:
    get:
      summary: Get My Courses
      responses:
        "200":
          description: Success Get My Courses
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Thu, 15 Jan 2026 06:38:24 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Student
        - Courses
  /api/courses/{courseId}/enroll:
    post:
      summary: Enroll Course
      responses:
        "200":
          description: Enroll Free Course
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Thu, 15 Jan 2026 04:12:45 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Student
        - Courses
    parameters:
      - name: courseId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "1"
  /api/certificates/verify/{certificateNumber}:
    get:
      summary: Verify Certificate (Public)
      responses: {}
      tags:
        - Student
        - Certificate
    parameters:
      - name: certificateNumber
        in: path
        required: true
        deprecated: false
        schema: {}
        example: CERT-2026-001234
  /api/my-certificates:
    get:
      summary: Get My Certificates
      responses: {}
      tags:
        - Student
        - Certificate
  /api/certificates/{id}:
    get:
      summary: Get Certificate Detail
      responses: {}
      tags:
        - Student
        - Certificate
    parameters:
      - name: id
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "2"
  /api/certificates/{id}/download:
    get:
      summary: Download Certificate PDF
      responses: {}
      tags:
        - Student
        - Certificate
    parameters:
      - name: id
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "1"
  /api/dashboard/stats:
    get:
      summary: Get Stats
      responses:
        "200":
          description: Stats
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 16 Jan 2026 07:12:19 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Student
  /api/dashboard/continue-learning:
    get:
      summary: Get Last Learn
      responses:
        "200":
          description: Success Get Last Learn
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 16 Jan 2026 04:05:21 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Student
  /api/admin/courses:
    get:
      summary: Get List All Courses
      parameters:
        - name: status
          in: query
          required: false
          deprecated: false
          schema: {}
        - name: search
          in: query
          required: false
          deprecated: false
          schema: {}
        - name: instructor
          in: query
          required: false
          deprecated: false
          schema: {}
        - name: per_page
          in: query
          required: false
          deprecated: false
          schema: {}
          example: "5"
      responses:
        "200":
          description: Success Get List All Courses
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Tue, 27 Jan 2026 06:12:45 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Courses
    post:
      summary: Create Courses
      responses:
        "201":
          description: Success Create Courses
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Tue, 27 Jan 2026 06:42:27 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Courses
  /api/admin/courses/{id}:
    get:
      summary: Get Course Detail
      responses:
        "200":
          description: Success Get Course Detail
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Tue, 27 Jan 2026 06:18:28 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Courses
    parameters:
      - name: id
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "4"
    put:
      summary: Update Course
      responses:
        "200":
          description: Success Update Course
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Tue, 27 Jan 2026 07:01:54 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Courses
    delete:
      summary: Delete Course
      responses:
        "200":
          description: Success Delete Course
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Tue, 27 Jan 2026 07:57:10 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Courses
  /api/admin/courses/{courseId}/sections:
    get:
      summary: Get List Sections in Course
      responses:
        "200":
          description: Success Get List Sections in Course
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Tue, 27 Jan 2026 08:46:14 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Content Management
        - Section CRUD
    parameters:
      - name: courseId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "1"
  /api/admin/courses/1/sections:
    post:
      summary: Create Section
      responses:
        "200":
          description: Success Create Section
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Sat, 10 Jan 2026 14:22:05 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Content Management
        - Section CRUD
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
            example:
              title: Testing
  /admin/sections/{sectionId}:
    put:
      summary: Update Section
      responses:
        "200":
          description: Success Update Section
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Tue, 27 Jan 2026 13:15:34 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Content Management
        - Section CRUD
    parameters:
      - name: sectionId
        in: path
        required: true
        schema:
          type: integer
        example: "1"
  /api/admin/sections/{sectionId}:
    delete:
      summary: Delete Section
      responses:
        "200":
          description: Delete Section
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Tue, 27 Jan 2026 13:17:16 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Content Management
        - Section CRUD
    parameters:
      - name: sectionId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "1"
  /api/admin/sections/:{sectionId}/lessons:
    post:
      summary: Create Lesson Link Video Type
      responses:
        "200":
          description: Success Link Video Type
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Sat, 10 Jan 2026 14:34:27 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Content Management
        - Lesson CRUD
    parameters:
      - name: ":sectionId"
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "2"
  /api/admin/sections/{sectionId}/lessons:
    get:
      summary: Get List Lesson in Section
      responses:
        "200":
          description: Success Get List Lesson in Section
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Wed, 28 Jan 2026 09:56:31 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Content Management
        - Lesson CRUD
    parameters:
      - name: sectionId
        in: path
        required: true
        schema:
          type: integer
        example: "3"
  /api/admin/lessons/{lessonId}:
    get:
      summary: Get Lesson Detail
      responses:
        "200":
          description: Success Get Lesson Detail
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Wed, 28 Jan 2026 10:00:59 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Content Management
        - Lesson CRUD
    parameters:
      - name: lessonId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "5"
    put:
      summary: Update Lesson Link Video Type Copy
      responses:
        "200":
          description: Success Update Lesson Link Video Type Copy
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Wed, 28 Jan 2026 10:31:24 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Content Management
        - Lesson CRUD
    delete:
      summary: Delete Lesson
      responses:
        "200":
          description: Success Delete Lesson
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Wed, 28 Jan 2026 10:33:16 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Content Management
        - Lesson CRUD
  /api/admin/lessons/{lessonId}/quiz:
    get:
      summary: Get Quiz with All Questions
      responses:
        "200":
          description: Success Get Quiz with All Questions
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Wed, 28 Jan 2026 10:45:08 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Content Management
        - Quiz Builder
    parameters:
      - name: lessonId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "12"
  /api/admin/lessons/{lessonId}/questions:
    post:
      summary: Add Question
      responses:
        "201":
          description: Success Add Question
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Wed, 28 Jan 2026 11:54:11 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Content Management
        - Quiz Builder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                question_text:
                  type: string
                points:
                  type: integer
                sequence:
                  type: integer
                options:
                  type: array
                  items:
                    type: object
                    properties:
                      option_text:
                        type: string
                      is_correct:
                        type: boolean
            example:
              question_text: Apakah pertanyaan ini berhasil ditambahkan?
              points: 10
              sequence: 2
              options:
                - option_text: ya
                  is_correct: true
                - option_text: tidak
                  is_correct: false
                - option_text: mungkin
                  is_correct: false
    parameters:
      - name: lessonId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "8"
  /api/admin/questions/{questionId}:
    put:
      summary: Update Question
      responses:
        "200":
          description: Success Update Question
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Wed, 28 Jan 2026 12:08:27 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Content Management
        - Quiz Builder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                question_text:
                  type: string
                points:
                  type: integer
                options:
                  type: array
                  items:
                    type: object
                    properties:
                      option_text:
                        type: string
                      is_correct:
                        type: boolean
            example:
              question_text: Updated question text?
              points: 10
              options:
                - option_text: New 1
                  is_correct: true
                - option_text: Option 1
                  is_correct: false
    parameters:
      - name: questionId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "3"
    delete:
      summary: Delete Question
      responses:
        "200":
          description: Succes Delete Question
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Wed, 28 Jan 2026 12:13:27 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Content Management
        - Quiz Builder
  /api/admin/lessons/{lessonId}/questions/reorder:
    post:
      summary: Reorder Questions (Drag & Drop)
      responses:
        "200":
          description: Success Reorder Questions (Drag & Drop)
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Thu, 29 Jan 2026 16:12:07 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Content Management
        - Quiz Builder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                questions:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      sequence:
                        type: integer
            example:
              questions:
                - id: 3
                  sequence: 1
                - id: 1
                  sequence: 2
                - id: 2
                  sequence: 3
    parameters:
      - name: lessonId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "3"
  /api/admin/courses/{courseId}/signatures:
    get:
      summary: Get List Signatures
      responses:
        "200":
          description: Success Get List Signatures
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 30 Jan 2026 10:47:23 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Certificate Management
        - Certificate Signatures
    parameters:
      - name: courseId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "1"
    post:
      summary: Create Signature
      responses:
        "201":
          description: Success Create Signature
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 30 Jan 2026 10:51:16 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Certificate Management
        - Certificate Signatures
  /api/admin/courses/{courseId}/signatures/{signatueId}:
    put:
      summary: Update Signature
      responses:
        "200":
          description: Success Update Signature
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 30 Jan 2026 10:57:22 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Certificate Management
        - Certificate Signatures
    parameters:
      - name: courseId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "1"
      - name: signatueId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "3"
    delete:
      summary: Delete Signature
      responses:
        "200":
          description: Success Delete Signature
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 30 Jan 2026 10:58:58 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Certificate Management
        - Certificate Signatures
  /api/admin/courses/{courseId}/signatures/reorder:
    post:
      summary: Reorder Signatures
      responses: {}
      tags:
        - Admin
        - Certificate Management
        - Certificate Signatures
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                signatures:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      order:
                        type: integer
            example:
              signatures:
                - id: 2
                  order: 1
                - id: 1
                  order: 2
                - id: 3
                  order: 3
    parameters:
      - name: courseId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "1"
  /api/admin/courses/{courseId}/certificate:
    get:
      summary: Get Certificate Config
      responses:
        "200":
          description: Success Get Certificate Config
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Thu, 29 Jan 2026 16:17:18 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Certificate Management
    parameters:
      - name: courseId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "1"
  /api/certificate-preview/1:
    get:
      summary: Get Certificate Preview
      responses: {}
      tags:
        - Admin
        - Certificate Management
  /api/admin/courses/{courseId}/certificate-config:
    post:
      summary: Create/Update Certificate Config
      responses:
        "200":
          description: Success Create/Update Certificate Config
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 30 Jan 2026 10:06:21 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Certificate Management
    parameters:
      - name: courseId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: "1"
    delete:
      summary: Delete Certificate Config
      responses:
        "200":
          description: Success Delete Certificate Config
          headers:
            Host:
              schema:
                type: string
              example: 127.0.0.1:8000
            Connection:
              schema:
                type: string
              example: close
            X-Powered-By:
              schema:
                type: string
              example: PHP/8.4.1
            Cache-Control:
              schema:
                type: string
              example: no-cache, private
            Date:
              schema:
                type: string
              example: Fri, 30 Jan 2026 10:45:20 GMT
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      tags:
        - Admin
        - Certificate Management
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
security:
  - BearerAuth: []
